name: Hexo-Theme-Type auto test

on: workflow_dispatch
  
jobs:
  theme_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: hexo test
      run: |
        npm install hexo-cli -g
        mkdir hexo-test
        cd hexo-test
        hexo init
        npm install hexo-deployer-git --save
        npm install hexo-theme-type --save
        npm install
        sudo cp -v ./node_modules/hexo-theme-type/_config_test.yml ./_config.type.yml
        sudo cp -v ./node_modules/hexo-theme-type/assets/_config.yml ./_config.yml
        git clone https://github.com/hexojs/hexo-theme-unit-test.git unit-test
        cp -r unit-test/source/_posts /source/_posts
        hexo g
        cd public
        git init
        git config --global push.default matching
        git config --global user.email "hiaiokr@gmail.com"
        git config --global user.name "aiokr"
        git add --all .
        git commit -m "Auto Builder of Type Live Preivew"
        git push --force "https://${{secrets.THEME_LIVE_PREIVEW}}@github.com/photup/type-live-preivew.git" master
